import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";

export async function GET(req: Request) {
  const session = await getSession();
  if (!session || session.role !== "admin") return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(req.url);
  const studentId = String(searchParams.get("studentId") || "");
  if (!studentId) return NextResponse.json({ error: "studentId required" }, { status: 400 });

  const student = db.prepare(`
    SELECT s.id, s.name, s.grade, s.progress_percent, s.current_focus, s.recent_activity,
           t.name as teacher_name
    FROM students s
    JOIN teachers t ON s.teacher_id = t.id
    WHERE s.id = ?
  `).get(studentId) as any;

  if (!student) return NextResponse.json({ error: "Student not found" }, { status: 404 });

  const report = {
    generatedAt: new Date().toISOString(),
    reportType: "State Compliance Progress Snapshot",
    school: session.school,
    student: {
      id: student.id,
      name: student.name,
      grade: student.grade,
      progressPercent: student.progress_percent,
      currentFocus: student.current_focus,
      recentActivity: student.recent_activity,
    },
    educator: student.teacher_name,
    note: "Generated by school admin portal. Individual editing data remains restricted."
  };

  return NextResponse.json({ ok: true, report });
}
